spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/chaing
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 중엔 update, 운영엔 validate/none
    properties:
      hibernate:
        format_sql: true
        show_sql: true